# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('contentId', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topicId', models.AutoField(primary_key=True, serialize=False)),
                ('topicName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('complexity', models.TextField(max_length=20)),
                ('authorId', models.IntegerField()),
                ('rating', models.IntegerField(null=True)),
                ('contentId', models.IntegerField(primary_key=True, serialize=False)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('publishedDate', models.DateTimeField(blank=True, null=True)),
                ('topicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nittutorial.Topic')),
            ],
        ),
    ]
