# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nittutorial', '0004_auto_20160229_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=3)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='contentId',
            field=models.ForeignKey(db_column='contentId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nittutorial.Content'),
        ),
    ]
