# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nittutorial', '0006_auto_20160410_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='topicId',
            field=models.ForeignKey(db_column='topicId', on_delete=django.db.models.deletion.CASCADE, to='nittutorial.Topic'),
        ),
    ]
