# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nittutorial', '0007_auto_20160410_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topicName',
            field=models.CharField(max_length=200),
        ),
    ]
