# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nittutorial', '0008_auto_20160410_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorials',
            name='topicId',
        ),
    ]
