# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nittutorial', '0009_remove_tutorials_topicid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorials',
            name='topicId',
            field=models.ForeignKey(db_column='topicId', default=0, on_delete=django.db.models.deletion.CASCADE, to='nittutorial.Topic'),
            preserve_default=False,
        ),
    ]
