# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nittutorial', '0010_tutorials_topicid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorials',
            name='contentId',
        ),
        migrations.AddField(
            model_name='tutorials',
            name='content',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorials',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
