# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nittutorial', '0014_auto_20160410_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorials',
            old_name='conten',
            new_name='name',
        ),
    ]
