# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nittutorial', '0015_auto_20160410_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='name',
            field=models.CharField(default='abc', max_length=500),
        ),
    ]
