# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nittutorial', '0016_auto_20160410_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorials',
            old_name='name',
            new_name='content',
        ),
    ]
