# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nittutorial', '0017_auto_20160410_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorials',
            old_name='content',
            new_name='conten',
        ),
    ]
