# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nittutorial', '0019_auto_20160410_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorials',
            new_name='Tutorial',
        ),
    ]
